name: application build and test
on:
  push:
    branches:
      - master # or the name of your main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo to ubuntu
        uses: actions/checkout@v2

      - name: setup node enviroment 
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      
      - name: Install the required dependencies
        run: yarn install

      - name: testing the application
        run: yarn test

      - name: Start the application
        run: yarn start
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #     with:
    #       fetch-depth: 0
    #   - uses: sonarsource/sonarqube-scan-action@master
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    #   # If you wish to fail your job when the Quality Gate is red, uncomment the
    #   # following lines. This would typically be used to fail a deployment.
    #   - uses: sonarsource/sonarqube-quality-gate-action@master
    #     timeout-minutes: 5
    #     env:
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
