name: sonarqube integration with github actions

on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the application
        uses: actions/checkout@v2
        with:
          depth-fetch: 0

      - name: install all dependencies and test
        run: yarn install && yarn test

      - name: sonarqube scann
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}